service: sls-es-2

provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs12.x
  region: eu-west-2
  environment:
    DB_NAME: ${self:service}-db-${self:provider.stage}
  iamRoleStatements: ${file(${self:custom.templateDirectory}/iamRoleStatements.yml):iamRoleStatements}

custom:
  templateDirectory: ./serverless_templates

package:
  individually: true

functions:
  data: ${file(${self:custom.templateDirectory}/functions/data.yml)}
  stream: ${file(${self:custom.templateDirectory}/functions/stream.yml)}
  reindex-scan: ${file(${self:custom.templateDirectory}/functions/reindex-scan.yml)}
  reindex-stream: ${file(${self:custom.templateDirectory}/functions/reindex-stream.yml)}

resources:
  Resources:
    Vpc: ${file(${self:custom.templateDirectory}/resources/network.yml):Vpc}
    PrivateSubnet1: ${file(${self:custom.templateDirectory}/resources/network.yml):PrivateSubnet1}
    VpcSecurityGroup: ${file(${self:custom.templateDirectory}/resources/network.yml):VpcSecurityGroup}
    ESSecurityGroup: ${file(${self:custom.templateDirectory}/resources/network.yml):ESSecurityGroup}
    SlsEsTable: ${file(${self:custom.templateDirectory}/resources/dynamo.yml):SlsEsTable}
    ElasticSearchInstance: ${file(${self:custom.templateDirectory}/resources/elasticsearch.yml):ElasticSearchInstance}
